server:
  port: 8081

spring:
  application:
    name: FRIEND_BOOK-APPLICATION

  datasource:
    url: jdbc:mysql://localhost:3306/friend_book
    username: root
    password: Webkorps@123

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: nilkanthmanish0@gmail.com
    password: evgzdfhmwymwzlyl
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000
      refresh-token:
        expiration: 604800000
